[
"big",
"fat",
"broad shoulders",
"built",
"curvy",
"feminine",
"fit",
"heavyset",
"lean",
"long legs",
"tall",
"long torso",
"long",
"masculine",
"muscular",
"pear shaped",
"petite",
"proportioned",
"rectangular",
"round apple",
"short legs",
"short torso",
"short",
"skinny",
"small",
"stocky",
"sturdy",
"tall",
"attractive",
"sexy",
"hourglass"
]
