data_path: /home/nadav2/dev/data/CLIP2Shape/images
repo_path: /home/nadav2/dev/repos/CLIP2Shape
main_output_dir: /home/nadav2/dev/data/CLIP2Shape/outs/vids/optimization


optimization_cfg:

  # FLAME
  texture: #${repo_path}/Flame/flame2020/mesh.png
  model_type: flame
  text: chubby cheeks
  device: cuda
  total_steps: 500
  optimize_features: shape_params
  output_dir: ${main_output_dir}
  dist: 0.8
  elev: 0.0
  azim: 0.0
  lr: 0.01

  # SMPLX
  # texture: #${repo_path}/SMPLX/textures/smplx_texture_m_alb.png
  # model_type: smplx
  # device: cuda
  # text: muscular
  # total_steps: 500
  # optimize_features: betas
  # output_dir: ${main_output_dir}
  # dist: 2.5
  # elev: 15.0
  # azim: 0.0
  # lr: 0.01

  # SMAL
  # texture:  # keep empty for random texture
  # model_type: smal
  # device: cuda
  # text: donkey
  # total_steps: 700
  # optimize_features: beta
  # output_dir: ${main_output_dir}
  # dist: 3.8
  # elev: 15.0
  # azim: 0.0
  # lr: 0.01