defaults:
  - descriptors: smplx_neutral

images_dir: /home/nadav2/dev/data/CLIP2Shape/images/smplx_neutral_multiview_3k_uniform
out_path: /home/nadav2/dev/data/CLIP2Shape/outs/clustering_images/words_jsons