images_dir: /home/nadav2/dev/data/CLIP2Shape/images/flame_exp_e2e
out_path: /home/nadav2/dev/data/CLIP2Shape/outs/clustering_images/words_jsons


descriptors:  # FLAME - shape
  - "fat"
  - "thin"
  - "long neck"
  - "big forhead"
  - "nose sticking-out"
  - "big mouth"
  - "ears sticking-out"
  - "big eyebrows"
  - "small chin"
  - "long head"
  - "chubby cheeks"

# descriptors:  # FLAME - expression
#   - "happy"
#   - "sad"
#   - "angry"
#   - "surprised"
#   - "disgusted"
#   - "fearful"
#   - "neutral"
#   - "smiling"
#   - "serious"
#   - "pensive"
#   - "confused"
#   - "bored"
#   - "sleepy"
#   - "tired"
#   - "excited"
#   - "relaxed"
#   - "calm"
#   - "nervous"
#   - "worried"
#   - "scared"
#   - "open mouth"
#   - "raised eyebrows"
#   - "open eyes"



# descriptors:  # SMPLX - female
#   - "fat"
#   - "thin"
#   - "hourglass"
#   - "short"
#   - "long legs"
#   - "narrow waist"
#   - "skinny"
#   - "tall"
#   - "broad shoulders"
#   - "pear shaped"
#   - "average"
#   - "big"
#   - "curvy"
#   - "lean"
#   - "proportioned"
#   - "sexy"
#   - "fit"
#   - "heavyset"
#   - "petite"
#   - "small"

# descriptors:  # SMPLX - male
#   - "fat"
#   - "thin"
#   - "muscular"
#   - "short"
#   - "long legs"
#   - "narrow waist"
#   - "skinny"
#   - "tall"
#   - "rectangular"
#   - "pear shaped"
#   - "average"
#   - "big"
#   - "curvy"
#   - "lean"
#   - "masculine"
#   - "proportioned"
#   - "stocky"
#   - "sexy"
#   - "sturdy"
#   - "broad shoulders"
#   - "fit"
#   - "round apple"
#   - "built"
#   - "heavyset"
#   - "petite"
#   - "small"