defaults:
  - renderer_kwargs: flame_expression
  - train_kwargs: train

model_type: flame
gender: neutral
method: L2
mode: eval
optimize_feature: expression_params
data_path: /home/nadav2/dev/data/CLIP2Shape/images/flame_textured_exp
descriptors_clusters_json: /home/nadav2/dev/data/CLIP2Shape/outs/clustering_images/words_jsons/flame_expression.json
batch_size: 200
effect_threshold: 0.5

output_path: /home/nadav2/dev/data/CLIP2Shape/outs/descriptors_ablations/flame_expression
descriptors_options:
  - 2
  - 5
  - 10
  - 15
  - 20

renderer_kwargs:
    img_size: [1024, 1024]
    tex_path:
    texture_optimization: True