defaults:
    - renderer_kwargs: smplx

bs_dir: /home/nadav2/dev/data/CLIP2Shape/images/smplx_py3d_male/
model_path: /home/nadav2/dev/repos/Thesis/pre_production/smplx_male_end2end_15_desc.ckpt
output_dir: /home/nadav2/dev/data/CLIP2Shape/outs/sliders_vs_blendshapes/smplx_male/15_descriptors
gender: male
num_coeffs: 10
optimizing_feature: betas
model_type: smplx
display: True
write_videos: True

total_steps: 500
lr: 0.01

renderer_kwargs:
    img_size: [1024, 1024]
    tex_path: /home/nadav2/dev/repos/Thesis/SMPLX/textures/smplx_texture_m_alb.png